# Generated by Django 2.2 on 2019-04-19 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.IntegerField()),
                ('competencia', models.DateField()),
                ('observacao', models.TextField()),
                ('data_envio', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DadosArquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_linha', models.IntegerField()),
                ('num_registro', models.IntegerField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ArquivoChecagem',
            fields=[
                ('arquivo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='arquivo.Arquivo')),
                ('tipo_arquivo', models.CharField(default='checagem', max_length=150)),
            ],
            bases=('arquivo.arquivo',),
        ),
        migrations.CreateModel(
            name='ArquivoHistorico',
            fields=[
                ('arquivo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='arquivo.Arquivo')),
                ('tipo_arquivo', models.CharField(default='historico', max_length=150)),
            ],
            bases=('arquivo.arquivo',),
        ),
        migrations.CreateModel(
            name='DadosArquivoHistorico',
            fields=[
                ('dadosarquivo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='arquivo.DadosArquivo')),
                ('cod_conta', models.CharField(max_length=250)),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_arquivo', to='arquivo.ArquivoHistorico')),
            ],
            bases=('arquivo.dadosarquivo',),
        ),
        migrations.CreateModel(
            name='DadosArquivoChecagem',
            fields=[
                ('dadosarquivo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='arquivo.DadosArquivo')),
                ('cnpj', models.IntegerField()),
                ('indicador', models.CharField(max_length=250)),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_arquivo', to='arquivo.ArquivoChecagem')),
            ],
            bases=('arquivo.dadosarquivo',),
        ),
    ]
